import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Brain, 
  BarChart3, 
  PieChart, 
  TrendingUp, 
  Target, 
  Award, 
  CheckCircle,
  ArrowLeft,
  Download,
  Share2,
  RefreshCw
} from "lucide-react";
import { personalityTestService, TestResult, UserStats } from "../services/personalityTestService";
import NoTestsWarning from "./NoTestsWarning";


interface PersonalityTestResultsProps {
  userId: string;
  onBack: () => void;
  onRetakeTest: () => void;
}

export default function PersonalityTestResults({ userId, onBack, onRetakeTest }: PersonalityTestResultsProps) {
  const [results, setResults] = useState<TestResult[]>([]);
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<UserStats>({
    totalTests: 0,
    averageScore: 0,
    topTrait: '',
    completedThisMonth: 0,
    lastTestDate: ''
  });

  useEffect(() => {
    fetchResults();
  }, [userId]);

  const fetchResults = async () => {
    try {
      // Fetch real test results from the service
      const testResults = await personalityTestService.getUserTestHistory(userId);
      const userStats = await personalityTestService.getUserStats(userId);
      
      setResults(testResults);
      setStats(userStats);
      setLoading(false);
    } catch (error) {
      console.error('Error fetching results:', error);
      setLoading(false);
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-600 bg-green-100';
    if (score >= 80) return 'text-blue-600 bg-blue-100';
    if (score >= 70) return 'text-yellow-600 bg-yellow-100';
    return 'text-red-600 bg-red-100';
  };

  const getLevelColor = (level: string) => {
    switch (level.toLowerCase()) {
      case 'excellent': return 'bg-green-100 text-green-800';
      case 'high': return 'bg-blue-100 text-blue-800';
      case 'good': return 'bg-yellow-100 text-yellow-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const generateDetailedReport = (testResult: TestResult) => {
    const reportContent = `
# Detailed Personality Assessment Report
## Student Assessment Results

### Test Information
- **Assessment Date:** ${new Date(testResult.completed_date).toLocaleDateString()}
- **Trait Assessed:** ${testResult.trait.replace('_', ' ').toUpperCase()}
- **Score Achieved:** ${testResult.score}%
- **Performance Level:** ${testResult.level}

### Detailed Analysis

#### Key Strengths Identified
${testResult.strengths.map((strength, index) => `${index + 1}. ${strength}`).join('\n')}

#### Career Recommendations
Based on your assessment results, the following career paths are recommended:
${testResult.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

### Performance Insights
- **Score Range:** ${testResult.score}% (${testResult.level} level)
- **Strengths Count:** ${testResult.strengths.length} key strengths identified
- **Career Options:** ${testResult.recommendations.length} recommended paths

### Development Recommendations
1. **Focus Areas:** Continue developing your ${testResult.trait.replace('_', ' ')} skills
2. **Career Planning:** Explore opportunities in ${testResult.recommendations.slice(0, 2).join(' and ')}
3. **Skill Development:** Consider additional training in areas that complement your strengths
4. **Progress Tracking:** Take follow-up assessments to monitor your development

### Next Steps
- Review your strengths and identify areas for further development
- Research the recommended career paths to find the best fit
- Consider taking additional assessments to explore other personality traits
- Connect with career counselors for personalized guidance

---
*This report was generated by the TVET Assessment System*
*For questions about your results, contact your academic advisor*
    `.trim();

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `detailed-assessment-report-${testResult.trait}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <div className="w-8 h-8 border-4 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
          </div>
          <h2 className="text-xl font-semibold text-gray-800 mb-2">Loading Results</h2>
          <p className="text-gray-600">Please wait while we analyze your assessment results...</p>
        </div>
      </div>
    );
  }

  // Show warning if no tests have been taken
  if (results.length === 0) {
    return <NoTestsWarning onStartTest={onRetakeTest} />;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Microsoft Outlook-style Header */}
      <div className="bg-white border-b border-gray-200 shadow-sm">
        <div className="flex items-center justify-between px-6 py-4">
          <div className="flex items-center space-x-4">
            <div className="w-8 h-8 bg-gradient-to-r from-blue-500 to-purple-500 rounded-lg flex items-center justify-center">
              <Brain className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-2xl font-semibold text-gray-800">Personality Assessment Results</h1>
          </div>
          <div className="flex items-center space-x-3">
            <Button onClick={onBack} className="bg-blue-600 hover:bg-blue-700">
              <ArrowLeft className="w-4 h-4 mr-2" />
              View Dashboard
            </Button>
            <Button variant="outline" onClick={onRetakeTest}>
              <RefreshCw className="w-4 h-4 mr-2" />
              Take New Test
            </Button>
          </div>
        </div>
      </div>

      <div className="p-6">
        {/* Stats Overview */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <Card className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Tests</p>
                <p className="text-2xl font-bold text-gray-900">{stats.totalTests}</p>
              </div>
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <Brain className="w-6 h-6 text-blue-600" />
              </div>
            </div>
          </Card>
          
          <Card className="p-6 border-l-4 border-l-green-500">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Latest Score</p>
                <p className="text-2xl font-bold text-green-600">{results.length > 0 ? results[results.length - 1].score : 0}%</p>
                <p className="text-xs text-gray-500">Most recent test</p>
              </div>
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                <Star className="w-6 h-6 text-green-600" />
              </div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Average Score</p>
                <p className="text-2xl font-bold text-gray-900">{stats.averageScore}%</p>
              </div>
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                <TrendingUp className="w-6 h-6 text-blue-600" />
              </div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Top Trait</p>
                <p className="text-lg font-bold text-gray-900 capitalize">{stats.topTrait.replace('_', ' ')}</p>
              </div>
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center">
                <Award className="w-6 h-6 text-purple-600" />
              </div>
            </div>
          </Card>
        </div>

        {/* Charts Section */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          {/* Score Distribution Chart */}
          <Card className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-800">Score Distribution</h3>
              <BarChart3 className="w-5 h-5 text-gray-400" />
            </div>
            <div className="space-y-4">
              {results.map((result) => (
                <div key={result.trait} className="flex items-center justify-between">
                  <span className="text-sm text-gray-600 capitalize">{result.trait.replace('_', ' ')}</span>
                  <div className="flex items-center space-x-2">
                    <div className="w-24 bg-gray-200 rounded-full h-2">
                      <div 
                        className="bg-blue-500 h-2 rounded-full" 
                        style={{width: `${result.score}%`}}
                      ></div>
                    </div>
                    <span className="text-sm font-medium text-gray-800 w-12">{result.score}%</span>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          {/* Trait Analysis Chart */}
          <Card className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-800">Trait Analysis</h3>
              <PieChart className="w-5 h-5 text-gray-400" />
            </div>
            <div className="space-y-4">
              {results.map((result) => (
                <div key={result.trait} className="flex items-center justify-between">
                  <div className="flex items-center">
                    <div className={`w-3 h-3 rounded-full mr-3 ${
                      result.score >= 90 ? 'bg-green-500' :
                      result.score >= 80 ? 'bg-blue-500' :
                      result.score >= 70 ? 'bg-yellow-500' : 'bg-red-500'
                    }`}></div>
                    <span className="text-sm text-gray-600 capitalize">{result.trait.replace('_', ' ')}</span>
                  </div>
                  <Badge className={getLevelColor(result.level)}>
                    {result.level}
                  </Badge>
                </div>
              ))}
            </div>
          </Card>
        </div>

        {/* Detailed Results */}
        <div className="mb-8">
          <h3 className="text-xl font-semibold text-gray-800 mb-6">Detailed Assessment Results</h3>
          <div className="space-y-6">
            {results.map((result) => (
              <Card key={result.trait} className="p-6">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h4 className="text-lg font-semibold text-gray-800 capitalize mb-2">
                      {result.trait.replace('_', ' ')} Assessment
                    </h4>
                    <p className="text-gray-600 text-sm">Completed on {new Date(result.completed_date).toLocaleDateString()}</p>
                  </div>
                  <div className="text-right">
                    <div className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium ${getScoreColor(result.score)}`}>
                      {result.score}%
                    </div>
                    <Badge className={`ml-2 ${getLevelColor(result.level)}`}>
                      {result.level}
                    </Badge>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <h5 className="text-sm font-semibold text-gray-800 mb-3">Key Strengths</h5>
                    <div className="space-y-2">
                      {result.strengths.map((strength, index) => (
                        <div key={index} className="flex items-center text-gray-700">
                          <CheckCircle className="w-4 h-4 text-green-500 mr-2" />
                          {strength}
                        </div>
                      ))}
                    </div>
                  </div>
                  <div>
                    <h5 className="text-sm font-semibold text-gray-800 mb-3">Career Recommendations</h5>
                    <div className="space-y-2">
                      {result.recommendations.map((rec, index) => (
                        <div key={index} className="flex items-center text-gray-700">
                          <Target className="w-4 h-4 text-blue-500 mr-2" />
                          {rec}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                <div className="mt-4 pt-4 border-t border-gray-200">
                  <div className="flex justify-end space-x-3">
                    <Button 
                      variant="outline" 
                      size="sm"
                      onClick={() => generateDetailedReport(result)}
                    >
                      <Download className="w-4 h-4 mr-2" />
                      Download Report
                    </Button>
                    <Button variant="outline" size="sm">
                      <Share2 className="w-4 h-4 mr-2" />
                      Share Results
                    </Button>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
